# Site settings
title: Blog of Chenglong Yang
email: 903761074@qq.com
description: 不积跬步无以至千里，不积小流无以成江海
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yangchenglong.github.io" # the base hostname & protocol for your site
# twitter_username: none
github_username:  yangchenglong
encoding: utf-8
# Build settings
# markdown: kramdown
markdown: redcarpet
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments

paginate: 8